// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Shop.Services.ProductApi.DbContexts;

#nullable disable

namespace Shop.Services.ProductApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shop.Services.ProductApi.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Desert",
                            Description = "Description1",
                            ImageUrl = "",
                            Name = "Producr1",
                            Price = 1.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Desert",
                            Description = "Description2",
                            ImageUrl = "",
                            Name = "Producr21",
                            Price = 2.0
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Desert3",
                            Description = "Description3",
                            ImageUrl = "",
                            Name = "Producr3",
                            Price = 3.0
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Desert4",
                            Description = "Description4",
                            ImageUrl = "",
                            Name = "Producr4",
                            Price = 4.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
